require("src/modules/fight/Hero")

require("src/modules/fight/hero/Iori")
require("src/modules/fight/hero/Iori2")
require("src/modules/fight/hero/Terry")
require("src/modules/fight/hero/Ryo")
require("src/modules/fight/hero/Robert")
require("src/modules/fight/hero/Mai")
require("src/modules/fight/hero/Clark")
require("src/modules/fight/hero/Athena")
require("src/modules/fight/hero/Shermie")
require("src/modules/fight/hero/Shermie2")
require("src/modules/fight/hero/Shingo")
require("src/modules/fight/hero/Andy")
require("src/modules/fight/hero/Daimon")
require("src/modules/fight/hero/Chang")
require("src/modules/fight/hero/King")
require("src/modules/fight/hero/Orochi")
require("src/modules/fight/hero/Yashiro")
require("src/modules/fight/hero/Yashiro2")
require("src/modules/fight/hero/Kensou")
require("src/modules/fight/hero/Chris")
require("src/modules/fight/hero/Chris2")
require("src/modules/fight/hero/Leona")
require("src/modules/fight/hero/Leona2")
require("src/modules/fight/hero/Chizuru")
require("src/modules/fight/hero/Yamazaki")
require("src/modules/fight/hero/Mary")
require("src/modules/fight/hero/Kyo")
require("src/modules/fight/hero/Chin")
require("src/modules/fight/hero/Benimaru")
require("src/modules/fight/hero/Billy")
require("src/modules/fight/hero/Choi")
require("src/modules/fight/hero/Joe")
require("src/modules/fight/hero/Kim")
require("src/modules/fight/hero/Ralf")
require("src/modules/fight/hero/Yuri")





--小怪
require("src/modules/fight/hero/JieTouHunHun")
require("src/modules/fight/hero/TianTongKai")
require("src/modules/fight/hero/TiaoZi")
require("src/modules/fight/hero/LianDaoPan")
require("src/modules/fight/hero/NanManQuanWang")
require("src/modules/fight/hero/YinYueShaoNv")
