module(...,package.seeall)
Config={
[2401] = {name=2401, lock=3, action="站立轻拳", target={}, loop=0, speedX=0, isJump=false, shader="", effect="", sound="", beBeat={"forward_run","stand"}, rangeMin=0, rangeMax=145, hitEvent={[3]={reac="hit_light_a",effect="轻受击",deffect="防御1",deback=20,back=15,delayA=0.04,delayB=0.04,shock=1}}, noHitEvent={}, },
[2402] = {name=2402, lock=3, action="站立轻脚", target={}, loop=0, speedX=0, isJump=false, shader="", effect="", sound="", beBeat={"forward_run","stand"}, rangeMin=0, rangeMax=130, hitEvent={[2]={reac="hit_light_a",effect="轻受击",deffect="防御1",deback=20,back=15,delayA=0.12,delayB=0.04,shock=3}}, noHitEvent={}, },
[2403] = {name=2403, lock=3, action="站立重拳", target={}, loop=0, speedX=0, isJump=false, shader="", effect="", sound="", beBeat={"forward_run","stand"}, rangeMin=0, rangeMax=165, hitEvent={[5]={reac="hit_heavy_b",effect="重受击",deffect="防御1",deback=30,back=20,delayA=0.10,delayB=0.06,shock=1,shock=3}}, noHitEvent={}, },
[2404] = {name=2404, lock=3, action="站立重脚", target={}, loop=0, speedX=0, isJump=false, shader="", effect="", sound="", beBeat={"forward_run","stand"}, rangeMin=0, rangeMax=160, hitEvent={[8]={reac="hit_heavy_b",effect="重受击",deffect="防御1",deback=30,back=30,delayA=0.02,delayB=0.02},[5]={reac="hit_heavy_a",effect="重受击",deffect="防御1",deback=30,back=30,delayA=0.02,delayB=0.02,shock=1}}, noHitEvent={}, },
[2405] = {name=2405, lock=3, action="跳跃轻拳", target={}, loop=0, speedX=0, isJump=true, shader="", effect="", sound="", beBeat={"forward_run","stand"}, rangeMin=0, rangeMax=155, hitEvent={[5]={reac="hit_light_a",effect="轻受击",deffect="防御1",deback=20,back=15,delayA=0.08,delayB=0.04,shock=1}}, noHitEvent={}, },
[2406] = {name=2406, lock=3, action="超重击", target={}, loop=0, speedX=0, isJump=false, shader="", effect="", sound="", beBeat={"forward_run","stand"}, rangeMin=0, rangeMax=150, hitEvent={[6]={reac="hit_fly_a",effect="轻受击",deffect="防御1",deback=20,back=50,delayA=0.12,delayB=0.10,shock=7,flash=1,speed=-650}}, noHitEvent={}, },
[2407] = {name=2407, lock=3, action="神指", target={}, loop=0, speedX=0, isJump=false, shader="", effect="", sound="", beBeat={"forward_run","stand"}, rangeMin=0, rangeMax=140, hitEvent={[4]={reac="hit_fly_a",effect="重受击",deffect="防御1",deback=30,back=20,delayA=0.12,delayB=0.08,speed=-550,shock=7,flash=1}}, noHitEvent={[6]={shock=3},[7]={shock=3},[8]={shock=1}}, },
[2408] = {name=2408, lock=3, action="灵气柱_动作", target={}, loop=0, speedX=0, isJump=false, shader="", effect="", sound="", beBeat={"forward_run","stand"}, rangeMin=100, rangeMax=999, hitEvent={[0]={reac="hit_fly_a",effect="重受击",deffect="防御1",deback=30,speed=-400,delayA=0.20,delayB=0.12,flash=1,shock=8,}}, noHitEvent={[7]={shock=7},[8]={shock=3}}, },
[2409] = {name=2409, lock=3, action="阳光普照", target={}, loop=0, speedX=0, isJump=false, shader="", effect="OrochiPower", sound="orochi/Yangguangpuzhao.mp3", beBeat={"forward_run","stand"}, rangeMin=0, rangeMax=999, hitEvent={["8,12,16,20,24,28,32,36,40,44"]={reac="hit_heavy_b",effect="重受击",deffect="防御1",deback=30,delayA=0.02,delayB=0.02,shock=3,flash=1,back=5},["10,14,18,22,26,30,34,38,42"]={reac="hit_heavy_a",effect="重受击",deffect="防御1",deback=30,delayA=0.02,delayB=0.02,shock=3,back=9},["46"]={reac="hit_fly_a",effect="重受击",deffect="防御1",deback=30,delayA=0.02,delayB=0.02,shock=8,flash=1,speed=-700}}, noHitEvent={[47]={shock=7,flash=1},[48]={shock=3},[49]={shock=3}}, },
[2410] = {name=2410, lock=3, action="黑粒子_动作", target={}, loop=0, speedX=0, isJump=false, shader="", effect="", sound="", beBeat={"forward_run","stand"}, rangeMin=0, rangeMax=999, hitEvent={[0]={reac="hit_heavy_a",effect="重受击",deffect="防御1",deback=30,delayA=0.02,delayB=0.02,back=50,flash=1,shock=3}}, noHitEvent={}, },
[2411] = {name=2411, lock=3, action="反弹盾_动作", target={}, loop=0, speedX=0, isJump=false, shader="", effect="", sound="", beBeat={"forward_run","stand"}, rangeMin=150, rangeMax=999, hitEvent={[0]={reac="hit_fly_a",effect="重受击",deffect="防御1",deback=30,delayB=0.20,speed=-530,shock=3}}, noHitEvent={[40]={shock=3}}, },
[2412] = {name=2412, lock=3, action="掏魂_大招释放阶段", target={}, loop=0, speedX=0, isJump=false, shader="", effect="", sound="", beBeat={"forward_run","stand"}, rangeMin=0, rangeMax=999, hitEvent={[10]={reac="be_caught",forceReac=true,effect="抓起",deffect="防御1"}}, noHitEvent={}, },
[2414] = {name=2414, lock=3, action="掏魂_攻击阶段", target={}, loop=0, speedX=0, isJump=false, shader="", effect="", sound="orochi/Taohun.mp3", beBeat={"stand"}, rangeMin=0, rangeMax=145, hitEvent={["7"]={reac="hit_heavy_b",effect="飙血",deffect="防御1",deback=20,back=5,delayA=0.20,delayB=2,shock=3,flash=1},["32"]={reac="hit_fly_a",effect="重受击",deffect="防御1",deback=20,speed=-530,delayA=0.04,delayB=0.04,flash=1,shock=8}}, noHitEvent={[33]={shock=8,flash=1},[34]={shock=7},[35]={shock=3},[36]={shock=3},[37]={shock=1}}, },
[2415] = {name=2415, lock=3, action="跳跃轻拳", target={}, loop=0, speedX=360, isJump=true, shader="", effect="", sound="", beBeat={"forward_run","stand"}, rangeMin=0, rangeMax=225, hitEvent={[5]={reac="hit_light_a",effect="轻受击",deffect="防御1",deback=20,back=15,delayA=0.04,delayB=0.04}}, noHitEvent={}, },
[2416] = {name=2416, lock=3, action="跳跃轻拳", target={}, loop=0, speedX=-360, isJump=true, shader="", effect="", sound="", beBeat={"forward_run","stand"}, rangeMin=0, rangeMax=155, hitEvent={[5]={reac="hit_light_a",effect="轻受击",deffect="防御1",deback=20,back=15,delayA=0.04,delayB=0.04}}, noHitEvent={}, },
["assist"] = {name="assist", lock=3, action="援助动作", target={}, loop=0, speedX=0, isJump=false, shader="", effect="", sound="", beBeat={"forward_run","stand"}, rangeMin=0, rangeMax=0, hitEvent={}, noHitEvent={}, },
}
